name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Backend install & lint
        working-directory: backend
        run: |
          npm ci || npm install
          node -v
          npm run -s start -- --help || true

      - name: Frontend build
        working-directory: frontend
        run: |
          npm ci || npm install
          npm run build
